Add radosgw:certificates relation with vault:certificates
openstack-charmers/openstack-bundles pull request #191
Opened 2020-10-05 10:37 UTC by dardelean

Add radosgw:certificates relation with vault:certificates for openstack-base-bionic-ussuri-ovn

2021-02-01 15:37 UTC, AurelienLourot requested changes
Thanks, why only this particular bundle?

2021-02-01 15:43 UTC, dardelean commented
This is the only bundle that was not active on deployment. Guess the Focal bundle worked back then.

2021-05-28 11:47 UTC, AurelienLourot commented
Sorry for the delay: this totally makes sense and indeed this relation is present in all the more recent OVN bundles. Validating on our amd64 lab and landing. Thanks!

2021-05-28 11:48 UTC, AurelienLourot approved these changes

2021-05-28 20:42 UTC, merged