Drop legacy charm urls from bundles
openstack-charmers/openstack-bundles pull request #239
Opened 2022-06-03 15:32 UTC by wolsen

Previously, charm urls could reference Ubuntu series as part of the
charm that was being delivered (e.g. <team>/<series>/<charm>). Some
of the legacy bundles in this repository used this particular URL
schema to target specific series of charms.

However, this was deprecated as the series was added to the charm
metadata and the new charmhub store does not support this particular
API and subsequently causes the lint tests to fail as a result.

This removes all of these urls from the bundles in order to allow
the lint checks to pass.

Signed-off-by: Billy Olsen <billy.olsen@gmail.com>

2022-06-03 17:46 UTC, freyes requested changes
There is a need for consistency between -next and non -next.

2022-06-03 17:46 UTC, freyes commented on development/openstack-base-xenial-ocata/bundle.yaml
> +    charm: cs:~openstack-charmers-next/ceph-mon
in other bundles you dropped the -next too.

2022-06-03 17:46 UTC, freyes commented on development/openstack-base-xenial-pike/bundle.yaml
> +    charm: cs:~openstack-charmers-next/ceph-mon
-next here.

2022-06-03 17:46 UTC, freyes commented on development/openstack-ha/masakari-mosci.yaml
> +    charm: cs:~openstack-charmers/placement
this bundle uses -next, it should be dropped too probably.

2022-06-03 17:46 UTC, freyes commented on development/openstack-refstack-xenial-ocata-ppc64el-alt/bundle.yaml
> +    charm: cs:~openstack-charmers-next/percona-cluster
-next

2022-06-03 17:46 UTC, freyes commented on development/openstack-refstack-xenial-pike-ppc64el-alt/bundle.yaml
> +    charm: cs:~openstack-charmers-next/percona-cluster
-next

2022-06-03 17:46 UTC, freyes commented on development/openstack-telemetry-bionic-train/bundle.yaml
> +    charm: cs:~openstack-charmers/placement
this bundle uses -next

2022-06-03 17:46 UTC, freyes commented on development/openstack-telemetry-bionic-ussuri/bundle.yaml
> +    charm: cs:~openstack-charmers/placement
this bundle uses -next

2022-06-03 22:27 UTC, wolsen commented
> There is a need for consistency between -next and non -next.

Thanks Felipe for the review. Since these are all in the development dir, I have moved all of these to be consistent with openstack-charmers-next. There is a need to subsequently come through and update to use charmhub for the URLs or to archive the bundle, but for now this should provide consistency and get through the lint challenges.

2022-06-30 22:54 UTC, freyes approved these changes
LGTM, thanks Billy for doing the changes.

2022-06-30 22:54 UTC, merged